language: node_js
dist: trusty
sudo: false
node_js:
  - lts/carbon
  - stable
install:
  - travis_retry npm install
script:
  - npm run coverage
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
jobs:
  include:
    - stage: Lint
      script: npm run lint
      node_js: lts/carbon
