language: node_js
branches:
  except:
    - /^v[0-9]/
node_js:
  - lts/argon
  - lts/boron
  - stable
script:
  - make test-travis
before_script:
  - sudo apt-get install bc
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
