name: Create GitHub Release

on:
  workflow_run:
    workflows: [NPM Release]
    types:
      - completed

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen # 18
          cache: 'npm'
      - run: node .release-notes.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
